# https://hub.docker.com/_/postgres
services:
  db:
    image: postgres:16-alpine # you can change to newer images if wanted
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
